# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright © 2024      GSI Helmholtzzentrum fuer Schwerionenforschung GmbH
#                       Matthias Kretz <m.kretz@gsi.de>

name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  VIM:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Indent test.cpp
        run: make check-vim

  Neovim:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        run: sudo apt-get install -y neovim

      - name: Indent test.cpp
        run: make check-nvim
